[package]
name = "laso_packet"
version = "0.2.0"
edition = "2021"

[dependencies]
heapless = "0.7.16"
ignore-result = "0.2.0"

[dev-dependencies]
quickcheck = "1"
quickcheck_macros = "1"
assert_hex = "0.2.2"
bitvec = { version = "1", default-features = false }
futures-lite = "2.6.0"
